In [2]:
from splinter import Browser
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import os

In [3]:
url='https://www.ofx.com/en-us/forex-news/historical-exchange-rates/monthly-average-rates/'
response=requests.get(url)
soup=bs(response.text,'html.parser')

In [4]:
# identify location of chromedriver and store it as a variable
driverPath = !which chromedriver
# Setup configuration variables to enable Splinter to interact with browser
executable_path = {'executable_path': driverPath[0]}
browser = Browser('chrome', **executable_path, headless=False)

In [5]:
res=soup.find_all('optgroup', label='All Currencies')[0]
option=res.find_all('option')
currencies=list(map(lambda o: o.text, option))
currencies

['AED UAE Dirham',
 'ARS Argentine Peso',
 'AUD Australian Dollar',
 'AZN Azerbaijani New Manat',
 'BGN Bulgarian Lev',
 'BHD Bahraini Dinar',
 'BND Brunei Dollar',
 'BRL Brazilian Real',
 'CAD Canadian Dollar',
 'CHF Swiss Franc',
 'CLP Chilean Peso',
 'CNH Chinese Renminbi Off-Shore',
 'CNY Chinese Yuan',
 'CZK Czech Koruna',
 'DKK Danish Kroner',
 'EGP Egyptian Pound',
 'EUR Euro',
 'FJD Fiji Dollar',
 'GBP British Pound',
 'HKD Hong Kong Dollar',
 'HUF Hungarian Forint',
 'IDR Indonesian Rupiah',
 'ILS Israeli New Shekel',
 'INR Indian Rupee',
 'JPY Japanese Yen',
 'KRW Korean Won',
 'KWD Kuwaiti Dinar',
 'LKR Sri Lanka Rupee',
 'MAD Moroccan Dirham',
 'MGA Malagasy Ariary',
 'MXN Mexican Peso',
 'MYR Malaysian Ringgit',
 'NOK Norwegian Kroner',
 'NZD New Zealand Dollar',
 'OMR Omani Rial',
 'PEN Peruvian Nuevo Sol',
 'PGK Papua New Guinea Kina',
 'PHP Philippine Peso',
 'PKR Pakistani Rupee',
 'PLN Polish Zloty',
 'RUB Russian Rouble',
 'SAR Saudi Arabian Riyal',
 'SBD Solomon Islands Dollar',
 'SCR Seychelles Rupee',
 'SEK Swedish Krona',
 'SGD Singapore Dollar',
 'THB Thai Baht',
 'TOP Tonga Pa`anga',
 'TRY Turkish Lira',
 'TWD New Taiwan Dollar',
 'TZS Tanzanian Shilling',
 'USD US Dollar',
 'VND Vietnamese Dong',
 'VUV Vanuatu Vatu',
 'WST Samoa Tala',
 'XOF CFA Franc (BCEAO)',
 'XPF Pacific Franc',
 'ZAR South African Rand']

In [6]:
currency_df=pd.DataFrame()
for currency in currencies:
    browser.visit(url)
    element=browser.find_by_xpath('//*[@id="#main"]/div[3]/div[1]/div/div/div/div[1]/div/div/div[1]').first
    element.click()
    currentcy_click=browser.find_by_text(currency)
    currentcy_click.click()
    button_click=browser.find_by_text('RETRIEVE DATA')
    button_click.click()
    temp_currency=pd.read_html(url)
    for index,row in temp_currency[0].iterrows():
#         currency_df['Date'].append(row[0])
#         currency_df['Rate'].append(row[1])
        currency_df = currency_df.append([[row[0],row[1],currency]])
    print(currency_df)

                    0                    1               2
0             Average             0.761312  AED UAE Dirham
0    January 31, 1990             0.781105  AED UAE Dirham
0   February 28, 1990             0.759321  AED UAE Dirham
0      March 31, 1990             0.755618  AED UAE Dirham
0      April 30, 1990             0.763662  AED UAE Dirham
..                ...                  ...             ...
0   November 30, 2019              0.68277  AED UAE Dirham
0   December 31, 2019             0.688739  AED UAE Dirham
0    January 08, 2020             0.694128  AED UAE Dirham
0             Average  {{results.average}}  AED UAE Dirham
0      {{point.Date}}       {{point.Rate}}  AED UAE Dirham

[364 rows x 3 columns]
                    0                    1                   2
0             Average             0.761312      AED UAE Dirham
0    January 31, 1990             0.781105      AED UAE Dirham
0   February 28, 1990             0.759321      AED UAE Dirham
0      March 31, 1990             0.755618      AED UAE Dirham
0      April 30, 1990             0.763662      AED UAE Dirham
..                ...                  ...                 ...
0   November 30, 2019              0.68277  ARS Argentine Peso
0   December 31, 2019             0.688739  ARS Argentine Peso
0    January 08, 2020             0.694128  ARS Argentine Peso
0             Average  {{results.average}}  ARS Argentine Peso
0      {{point.Date}}       {{point.Rate}}  ARS Argentine Peso

[728 rows x 3 columns]
                    0                    1                      2
0             Average             0.761312         AED UAE Dirham
0    January 31, 1990             0.781105         AED UAE Dirham
0   February 28, 1990             0.759321         AED UAE Dirham
0      March 31, 1990             0.755618         AED UAE Dirham
0      April 30, 1990             0.763662         AED UAE Dirham
..                ...                  ...                    ...
0   November 30, 2019              0.68277  AUD Australian Dollar
0   December 31, 2019             0.688739  AUD Australian Dollar
0    January 08, 2020             0.694128  AUD Australian Dollar
0             Average  {{results.average}}  AUD Australian Dollar
0      {{point.Date}}       {{point.Rate}}  AUD Australian Dollar

[1092 rows x 3 columns]
                    0                    1                          2
0             Average             0.761312             AED UAE Dirham
0    January 31, 1990             0.781105             AED UAE Dirham
0   February 28, 1990             0.759321             AED UAE Dirham
0      March 31, 1990             0.755618             AED UAE Dirham
0      April 30, 1990             0.763662             AED UAE Dirham
..                ...                  ...                        ...
0   November 30, 2019              0.68277  AZN Azerbaijani New Manat
0   December 31, 2019             0.688739  AZN Azerbaijani New Manat
0    January 08, 2020             0.694128  AZN Azerbaijani New Manat
0             Average  {{results.average}}  AZN Azerbaijani New Manat
0      {{point.Date}}       {{point.Rate}}  AZN Azerbaijani New Manat

[1456 rows x 3 columns]
                    0                    1                  2
0             Average             0.761312     AED UAE Dirham
0    January 31, 1990             0.781105     AED UAE Dirham
0   February 28, 1990             0.759321     AED UAE Dirham
0      March 31, 1990             0.755618     AED UAE Dirham
0      April 30, 1990             0.763662     AED UAE Dirham
..                ...                  ...                ...
0   November 30, 2019              0.68277  BGN Bulgarian Lev
0   December 31, 2019             0.688739  BGN Bulgarian Lev
0    January 08, 2020             0.694128  BGN Bulgarian Lev
0             Average  {{results.average}}  BGN Bulgarian Lev
0      {{point.Date}}       {{point.Rate}}  BGN Bulgarian Lev

[1820 rows x 3 columns]
                    0                    1                   2
0             Average             0.761312      AED UAE Dirham
0    January 31, 1990             0.781105      AED UAE Dirham
0   February 28, 1990             0.759321      AED UAE Dirham
0      March 31, 1990             0.755618      AED UAE Dirham
0      April 30, 1990             0.763662      AED UAE Dirham
..                ...                  ...                 ...
0   November 30, 2019              0.68277  BHD Bahraini Dinar
0   December 31, 2019             0.688739  BHD Bahraini Dinar
0    January 08, 2020             0.694128  BHD Bahraini Dinar
0             Average  {{results.average}}  BHD Bahraini Dinar
0      {{point.Date}}       {{point.Rate}}  BHD Bahraini Dinar

[2184 rows x 3 columns]
                    0                    1                  2
0             Average             0.761312     AED UAE Dirham
0    January 31, 1990             0.781105     AED UAE Dirham
0   February 28, 1990             0.759321     AED UAE Dirham
0      March 31, 1990             0.755618     AED UAE Dirham
0      April 30, 1990             0.763662     AED UAE Dirham
..                ...                  ...                ...
0   November 30, 2019              0.68277  BND Brunei Dollar
0   December 31, 2019             0.688739  BND Brunei Dollar
0    January 08, 2020             0.694128  BND Brunei Dollar
0             Average  {{results.average}}  BND Brunei Dollar
0      {{point.Date}}       {{point.Rate}}  BND Brunei Dollar

[2548 rows x 3 columns]
                    0                    1                   2
0             Average             0.761312      AED UAE Dirham
0    January 31, 1990             0.781105      AED UAE Dirham
0   February 28, 1990             0.759321      AED UAE Dirham
0      March 31, 1990             0.755618      AED UAE Dirham
0      April 30, 1990             0.763662      AED UAE Dirham
..                ...                  ...                 ...
0   November 30, 2019              0.68277  BRL Brazilian Real
0   December 31, 2019             0.688739  BRL Brazilian Real
0    January 08, 2020             0.694128  BRL Brazilian Real
0             Average  {{results.average}}  BRL Brazilian Real
0      {{point.Date}}       {{point.Rate}}  BRL Brazilian Real

[2912 rows x 3 columns]
                    0                    1                    2
0             Average             0.761312       AED UAE Dirham
0    January 31, 1990             0.781105       AED UAE Dirham
0   February 28, 1990             0.759321       AED UAE Dirham
0      March 31, 1990             0.755618       AED UAE Dirham
0      April 30, 1990             0.763662       AED UAE Dirham
..                ...                  ...                  ...
0   November 30, 2019              0.68277  CAD Canadian Dollar
0   December 31, 2019             0.688739  CAD Canadian Dollar
0    January 08, 2020             0.694128  CAD Canadian Dollar
0             Average  {{results.average}}  CAD Canadian Dollar
0      {{point.Date}}       {{point.Rate}}  CAD Canadian Dollar

[3276 rows x 3 columns]
                    0                    1                2
0             Average             0.761312   AED UAE Dirham
0    January 31, 1990             0.781105   AED UAE Dirham
0   February 28, 1990             0.759321   AED UAE Dirham
0      March 31, 1990             0.755618   AED UAE Dirham
0      April 30, 1990             0.763662   AED UAE Dirham
..                ...                  ...              ...
0   November 30, 2019              0.68277  CHF Swiss Franc
0   December 31, 2019             0.688739  CHF Swiss Franc
0    January 08, 2020             0.694128  CHF Swiss Franc
0             Average  {{results.average}}  CHF Swiss Franc
0      {{point.Date}}       {{point.Rate}}  CHF Swiss Franc

[3640 rows x 3 columns]
                    0                    1                 2
0             Average             0.761312    AED UAE Dirham
0    January 31, 1990             0.781105    AED UAE Dirham
0   February 28, 1990             0.759321    AED UAE Dirham
0      March 31, 1990             0.755618    AED UAE Dirham
0      April 30, 1990             0.763662    AED UAE Dirham
..                ...                  ...               ...
0   November 30, 2019              0.68277  CLP Chilean Peso
0   December 31, 2019             0.688739  CLP Chilean Peso
0    January 08, 2020             0.694128  CLP Chilean Peso
0             Average  {{results.average}}  CLP Chilean Peso
0      {{point.Date}}       {{point.Rate}}  CLP Chilean Peso

[4004 rows x 3 columns]
                    0                    1                               2
0             Average             0.761312                  AED UAE Dirham
0    January 31, 1990             0.781105                  AED UAE Dirham
0   February 28, 1990             0.759321                  AED UAE Dirham
0      March 31, 1990             0.755618                  AED UAE Dirham
0      April 30, 1990             0.763662                  AED UAE Dirham
..                ...                  ...                             ...
0   November 30, 2019              0.68277  CNH Chinese Renminbi Off-Shore
0   December 31, 2019             0.688739  CNH Chinese Renminbi Off-Shore
0    January 08, 2020             0.694128  CNH Chinese Renminbi Off-Shore
0             Average  {{results.average}}  CNH Chinese Renminbi Off-Shore
0      {{point.Date}}       {{point.Rate}}  CNH Chinese Renminbi Off-Shore

[4368 rows x 3 columns]
                    0                    1                 2
0             Average             0.761312    AED UAE Dirham
0    January 31, 1990             0.781105    AED UAE Dirham
0   February 28, 1990             0.759321    AED UAE Dirham
0      March 31, 1990             0.755618    AED UAE Dirham
0      April 30, 1990             0.763662    AED UAE Dirham
..                ...                  ...               ...
0   November 30, 2019              0.68277  CNY Chinese Yuan
0   December 31, 2019             0.688739  CNY Chinese Yuan
0    January 08, 2020             0.694128  CNY Chinese Yuan
0             Average  {{results.average}}  CNY Chinese Yuan
0      {{point.Date}}       {{point.Rate}}  CNY Chinese Yuan

[4732 rows x 3 columns]
                    0                    1                 2
0             Average             0.761312    AED UAE Dirham
0    January 31, 1990             0.781105    AED UAE Dirham
0   February 28, 1990             0.759321    AED UAE Dirham
0      March 31, 1990             0.755618    AED UAE Dirham
0      April 30, 1990             0.763662    AED UAE Dirham
..                ...                  ...               ...
0   November 30, 2019              0.68277  CZK Czech Koruna
0   December 31, 2019             0.688739  CZK Czech Koruna
0    January 08, 2020             0.694128  CZK Czech Koruna
0             Average  {{results.average}}  CZK Czech Koruna
0      {{point.Date}}       {{point.Rate}}  CZK Czech Koruna

[5096 rows x 3 columns]
                    0                    1                  2
0             Average             0.761312     AED UAE Dirham
0    January 31, 1990             0.781105     AED UAE Dirham
0   February 28, 1990             0.759321     AED UAE Dirham
0      March 31, 1990             0.755618     AED UAE Dirham
0      April 30, 1990             0.763662     AED UAE Dirham
..                ...                  ...                ...
0   November 30, 2019              0.68277  DKK Danish Kroner
0   December 31, 2019             0.688739  DKK Danish Kroner
0    January 08, 2020             0.694128  DKK Danish Kroner
0             Average  {{results.average}}  DKK Danish Kroner
0      {{point.Date}}       {{point.Rate}}  DKK Danish Kroner

[5460 rows x 3 columns]
                    0                    1                   2
0             Average             0.761312      AED UAE Dirham
0    January 31, 1990             0.781105      AED UAE Dirham
0   February 28, 1990             0.759321      AED UAE Dirham
0      March 31, 1990             0.755618      AED UAE Dirham
0      April 30, 1990             0.763662      AED UAE Dirham
..                ...                  ...                 ...
0   November 30, 2019              0.68277  EGP Egyptian Pound
0   December 31, 2019             0.688739  EGP Egyptian Pound
0    January 08, 2020             0.694128  EGP Egyptian Pound
0             Average  {{results.average}}  EGP Egyptian Pound
0      {{point.Date}}       {{point.Rate}}  EGP Egyptian Pound

[5824 rows x 3 columns]
                    0                    1               2
0             Average             0.761312  AED UAE Dirham
0    January 31, 1990             0.781105  AED UAE Dirham
0   February 28, 1990             0.759321  AED UAE Dirham
0      March 31, 1990             0.755618  AED UAE Dirham
0      April 30, 1990             0.763662  AED UAE Dirham
..                ...                  ...             ...
0   November 30, 2019              0.68277        EUR Euro
0   December 31, 2019             0.688739        EUR Euro
0    January 08, 2020             0.694128        EUR Euro
0             Average  {{results.average}}        EUR Euro
0      {{point.Date}}       {{point.Rate}}        EUR Euro

[6188 rows x 3 columns]
                    0                    1                2
0             Average             0.761312   AED UAE Dirham
0    January 31, 1990             0.781105   AED UAE Dirham
0   February 28, 1990             0.759321   AED UAE Dirham
0      March 31, 1990             0.755618   AED UAE Dirham
0      April 30, 1990             0.763662   AED UAE Dirham
..                ...                  ...              ...
0   November 30, 2019              0.68277  FJD Fiji Dollar
0   December 31, 2019             0.688739  FJD Fiji Dollar
0    January 08, 2020             0.694128  FJD Fiji Dollar
0             Average  {{results.average}}  FJD Fiji Dollar
0      {{point.Date}}       {{point.Rate}}  FJD Fiji Dollar

[6552 rows x 3 columns]
                    0                    1                  2
0             Average             0.761312     AED UAE Dirham
0    January 31, 1990             0.781105     AED UAE Dirham
0   February 28, 1990             0.759321     AED UAE Dirham
0      March 31, 1990             0.755618     AED UAE Dirham
0      April 30, 1990             0.763662     AED UAE Dirham
..                ...                  ...                ...
0   November 30, 2019              0.68277  GBP British Pound
0   December 31, 2019             0.688739  GBP British Pound
0    January 08, 2020             0.694128  GBP British Pound
0             Average  {{results.average}}  GBP British Pound
0      {{point.Date}}       {{point.Rate}}  GBP British Pound

[6916 rows x 3 columns]
                    0                    1                     2
0             Average             0.761312        AED UAE Dirham
0    January 31, 1990             0.781105        AED UAE Dirham
0   February 28, 1990             0.759321        AED UAE Dirham
0      March 31, 1990             0.755618        AED UAE Dirham
0      April 30, 1990             0.763662        AED UAE Dirham
..                ...                  ...                   ...
0   November 30, 2019              0.68277  HKD Hong Kong Dollar
0   December 31, 2019             0.688739  HKD Hong Kong Dollar
0    January 08, 2020             0.694128  HKD Hong Kong Dollar
0             Average  {{results.average}}  HKD Hong Kong Dollar
0      {{point.Date}}       {{point.Rate}}  HKD Hong Kong Dollar

[7280 rows x 3 columns]
                    0                    1                     2
0             Average             0.761312        AED UAE Dirham
0    January 31, 1990             0.781105        AED UAE Dirham
0   February 28, 1990             0.759321        AED UAE Dirham
0      March 31, 1990             0.755618        AED UAE Dirham
0      April 30, 1990             0.763662        AED UAE Dirham
..                ...                  ...                   ...
0   November 30, 2019              0.68277  HUF Hungarian Forint
0   December 31, 2019             0.688739  HUF Hungarian Forint
0    January 08, 2020             0.694128  HUF Hungarian Forint
0             Average  {{results.average}}  HUF Hungarian Forint
0      {{point.Date}}       {{point.Rate}}  HUF Hungarian Forint

[7644 rows x 3 columns]
                    0                    1                      2
0             Average             0.761312         AED UAE Dirham
0    January 31, 1990             0.781105         AED UAE Dirham
0   February 28, 1990             0.759321         AED UAE Dirham
0      March 31, 1990             0.755618         AED UAE Dirham
0      April 30, 1990             0.763662         AED UAE Dirham
..                ...                  ...                    ...
0   November 30, 2019              0.68277  IDR Indonesian Rupiah
0   December 31, 2019             0.688739  IDR Indonesian Rupiah
0    January 08, 2020             0.694128  IDR Indonesian Rupiah
0             Average  {{results.average}}  IDR Indonesian Rupiah
0      {{point.Date}}       {{point.Rate}}  IDR Indonesian Rupiah

[8008 rows x 3 columns]
                    0                    1                       2
0             Average             0.761312          AED UAE Dirham
0    January 31, 1990             0.781105          AED UAE Dirham
0   February 28, 1990             0.759321          AED UAE Dirham
0      March 31, 1990             0.755618          AED UAE Dirham
0      April 30, 1990             0.763662          AED UAE Dirham
..                ...                  ...                     ...
0   November 30, 2019              0.68277  ILS Israeli New Shekel
0   December 31, 2019             0.688739  ILS Israeli New Shekel
0    January 08, 2020             0.694128  ILS Israeli New Shekel
0             Average  {{results.average}}  ILS Israeli New Shekel
0      {{point.Date}}       {{point.Rate}}  ILS Israeli New Shekel

[8372 rows x 3 columns]
                    0                    1                 2
0             Average             0.761312    AED UAE Dirham
0    January 31, 1990             0.781105    AED UAE Dirham
0   February 28, 1990             0.759321    AED UAE Dirham
0      March 31, 1990             0.755618    AED UAE Dirham
0      April 30, 1990             0.763662    AED UAE Dirham
..                ...                  ...               ...
0   November 30, 2019              0.68277  INR Indian Rupee
0   December 31, 2019             0.688739  INR Indian Rupee
0    January 08, 2020             0.694128  INR Indian Rupee
0             Average  {{results.average}}  INR Indian Rupee
0      {{point.Date}}       {{point.Rate}}  INR Indian Rupee

[8736 rows x 3 columns]
                    0                    1                 2
0             Average             0.761312    AED UAE Dirham
0    January 31, 1990             0.781105    AED UAE Dirham
0   February 28, 1990             0.759321    AED UAE Dirham
0      March 31, 1990             0.755618    AED UAE Dirham
0      April 30, 1990             0.763662    AED UAE Dirham
..                ...                  ...               ...
0   November 30, 2019              0.68277  JPY Japanese Yen
0   December 31, 2019             0.688739  JPY Japanese Yen
0    January 08, 2020             0.694128  JPY Japanese Yen
0             Average  {{results.average}}  JPY Japanese Yen
0      {{point.Date}}       {{point.Rate}}  JPY Japanese Yen

[9100 rows x 3 columns]
                    0                    1               2
0             Average             0.761312  AED UAE Dirham
0    January 31, 1990             0.781105  AED UAE Dirham
0   February 28, 1990             0.759321  AED UAE Dirham
0      March 31, 1990             0.755618  AED UAE Dirham
0      April 30, 1990             0.763662  AED UAE Dirham

In [7]:
currency_df

                    0                    1                       2
0             Average             0.761312          AED UAE Dirham
0    January 31, 1990             0.781105          AED UAE Dirham
0   February 28, 1990             0.759321          AED UAE Dirham
0      March 31, 1990             0.755618          AED UAE Dirham
0      April 30, 1990             0.763662          AED UAE Dirham
..                ...                  ...                     ...
0   November 30, 2019              0.68277  ZAR South African Rand
0   December 31, 2019             0.688739  ZAR South African Rand
0    January 08, 2020             0.694128  ZAR South African Rand
0             Average  {{results.average}}  ZAR South African Rand
0      {{point.Date}}       {{point.Rate}}  ZAR South African Rand

[21112 rows x 3 columns]

In [9]:
currency_df=currency_df.rename(columns={0:'Date',1:'Rate',2:'Currency'})
currency_df

                 Date                 Rate                Currency
0             Average             0.761312          AED UAE Dirham
0    January 31, 1990             0.781105          AED UAE Dirham
0   February 28, 1990             0.759321          AED UAE Dirham
0      March 31, 1990             0.755618          AED UAE Dirham
0      April 30, 1990             0.763662          AED UAE Dirham
..                ...                  ...                     ...
0   November 30, 2019              0.68277  ZAR South African Rand
0   December 31, 2019             0.688739  ZAR South African Rand
0    January 08, 2020             0.694128  ZAR South African Rand
0             Average  {{results.average}}  ZAR South African Rand
0      {{point.Date}}       {{point.Rate}}  ZAR South African Rand

[21112 rows x 3 columns]

In [15]:
currency_df=currency_df.reset_index()
currency_df=currency_df[['Date','Rate','Currency']]
currency_df

                    Date                 Rate                Currency
0                Average             0.761312          AED UAE Dirham
1       January 31, 1990             0.781105          AED UAE Dirham
2      February 28, 1990             0.759321          AED UAE Dirham
3         March 31, 1990             0.755618          AED UAE Dirham
4         April 30, 1990             0.763662          AED UAE Dirham
...                  ...                  ...                     ...
21107  November 30, 2019              0.68277  ZAR South African Rand
21108  December 31, 2019             0.688739  ZAR South African Rand
21109   January 08, 2020             0.694128  ZAR South African Rand
21110            Average  {{results.average}}  ZAR South African Rand
21111     {{point.Date}}       {{point.Rate}}  ZAR South African Rand

[21112 rows x 3 columns]

In [12]:
currency_df.dtypes

Date        object
Rate        object
Currency    object
dtype: object

In [10]:
currency_df[currency_df.Rate.apply(lambda x: x.isnumeric())]

Empty DataFrame
Columns: [Date, Rate, Currency]
Index: []

In [8]:
currency_path = os.path.join('Data/currency.csv')
currency_df.to_csv(currency_path)

In [19]:
temp[0]

            Date (GMT)               Rate**
0              Average             0.761312
1     January 31, 1990             0.781105
2    February 28, 1990             0.759321
3       March 31, 1990             0.755618
4       April 30, 1990             0.763662
..                 ...                  ...
359  November 30, 2019              0.68277
360  December 31, 2019             0.688739
361   January 08, 2020             0.694128
362            Average  {{results.average}}
363     {{point.Date}}       {{point.Rate}}

[364 rows x 2 columns]

In [2]:
$ sqlitis 'select currencies.country, birth_rates.year, birth_rates.birthrate, food_production.foodproduction, currencies.currency, currency.rate from currencies,birth_rates,food_production,currency where currencies.currency=currency.currency and currencies.country_code=birth_rates.countrycode and currencies.country=food_production.country'

SyntaxError: invalid syntax (<ipython-input-2-7a484185e331>, line 1)

In [3]:
$ sqlitis 'select foo.name, bar.value from foo join bar'

SyntaxError: invalid syntax (<ipython-input-3-1015ed105449>, line 1)